// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwvFHFVjabUyp2Wi9nM2K78uuXkZbJDM',
    appId: '1:209396179097:web:dab1e7506a7cad51fa9808',
    messagingSenderId: '209396179097',
    projectId: 'ecom-mona',
    authDomain: 'ecom-mona.firebaseapp.com',
    storageBucket: 'ecom-mona.appspot.com',
    measurementId: 'G-DTVNS3JPKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjcBbIxOF7v8mQC6InzuwntZy4u0sVP4',
    appId: '1:209396179097:android:0a9fd2721aba2450fa9808',
    messagingSenderId: '209396179097',
    projectId: 'ecom-mona',
    storageBucket: 'ecom-mona.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWzRwUClsXFVzwyqw0HRpHecmi-TtV18',
    appId: '1:209396179097:ios:cd4e64272a24f9a2fa9808',
    messagingSenderId: '209396179097',
    projectId: 'ecom-mona',
    storageBucket: 'ecom-mona.appspot.com',
    iosClientId: '209396179097-hottq53ie09ihd3hkmq6lk9mqfcec5re.apps.googleusercontent.com',
    iosBundleId: 'com.myplate.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWzRwUClsXFVzwyqw0HRpHecmi-TtV18',
    appId: '1:209396179097:ios:cd4e64272a24f9a2fa9808',
    messagingSenderId: '209396179097',
    projectId: 'ecom-mona',
    storageBucket: 'ecom-mona.appspot.com',
    iosClientId: '209396179097-hottq53ie09ihd3hkmq6lk9mqfcec5re.apps.googleusercontent.com',
    iosBundleId: 'com.myplate.mynotes',
  );
}
